version: '3.3'

services:
  titan-sight:
    image: titan-sight:0.1.0
    container_name: titan-sight-apis
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./src:/app
      - ${HF_CACHE_DIR}:/root/.cache/huggingface
    networks:
      - net
    command: uvicorn app:app --host ${API_HOST} --port ${API_PORT} --workers ${NUM_WORKERS}

  searxng:
    image: searxng/searxng:2024.12.22-26097f444
    container_name: titan-sight-searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    networks:
      - net

  redis:
    image: redis/redis-stack-server:7.2.0-v13
    container_name: titan-sight-redis
    environment:
    - REDIS_ARGS=--save 60 1
    volumes: 
      - ${SOURCE_REDIS_VOLUME}:/data
    networks:
      - net
  
  mongodb:
    image: mongo:7.0-rc
    container_name: titan-sight-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${SOURCE_MONGO_VOLUME}:/data/db
    networks:
      - net

networks:
  net:
    external: true
    name: titan_sight_net

